name: build

on:
  push:
    # tags:
    #   - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    strategy:
      matrix:
        fedora: [42, 43]
        runs-on: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6
      - run: make ENGINE=docker SIGNAL_VERSION=v8.6.1 FEDORA_VERSION=${{ matrix.fedora }} # $GITHUB_REF_NAME
      - run: ls -lsah output/
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.fedora }}
          path: output/*.rpm

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
      - run: ls -Rlsah .
      - run: find . -name "*.rpm"

  # old-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - run: make ENGINE=docker SIGNAL_VERSION=$GITHUB_REF_NAME
  #     - run: sha256sum ./output/*.rpm > subject.checksums.txt
  #     - uses: actions/attest@v4
  #       with:
  #         subject-checksums: subject.checksums.txt
  #         predicate-type: "https://example.com/predicate/v1"
  #         predicate: "{}"
  #     - run: sed -i -E "s/[0-9]\.[0-9]{1,2}\.[0-9]/${GITHUB_REF_NAME#v}/g" .github/release-notes.md
  #     - name: Create GitHub Release
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #       run: gh release create "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY" --notes-file ".github/release-notes.md"
  #     - name: Upload artifact to GitHub Release
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #       run: gh release upload "$GITHUB_REF_NAME" ./output/*.rpm --repo "$GITHUB_REPOSITORY"
