name: build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

run-name: ${{ github.ref_name }}

permissions: {}

jobs:
  build:
    if: github.repository == 'BarbossHack/Signal-Desktop-Fedora'
    strategy:
      matrix:
        releasever: [43, 44, 45, rawhide]
        basearch: [x86_64, aarch64]
        include:
          - basearch: x86_64
            runner: ubuntu-latest
          - basearch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Print matrix
        run: |
          echo "releasever: ${{ matrix.releasever }}"
          echo "basearch: ${{ matrix.basearch }}"
          echo "runner: ${{ matrix.runner }}"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: make ENGINE=docker SIGNAL_VERSION=${GITHUB_REF_NAME} FEDORA_VERSION=${{ matrix.releasever }}
      - name: Install tools
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y createrepo-c dnf dnf-plugins-core
      - name: Import GPG key
        env:
          REPO_PRIVATE_KEY: ${{ secrets.REPO_PRIVATE_KEY }}
        run: echo "$REPO_PRIVATE_KEY" | gpg --batch --import
      - name: Create repository
        run: |
          mkdir -p repo/${{ matrix.releasever }}/${{ matrix.basearch }}
          cp output/*.rpm repo/${{ matrix.releasever }}/${{ matrix.basearch }}/
          cd repo/${{ matrix.releasever }}/${{ matrix.basearch }}
          export GPG_TTY=$(tty)
          rpm --define "_gpg_name 98AD93E28D7EB8B7F990BF2E55827D8FD54C06D0" --addsign *.rpm
          createrepo_c --update .
          gpg --detach-sign --armor repodata/repomd.xml
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: repo-${{ matrix.releasever }}-${{ matrix.basearch }}
          path: repo

  deploy-repository:
    needs: build
    if: github.repository == 'BarbossHack/Signal-Desktop-Fedora'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          merge-multiple: true
          path: repo
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: repo
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128

  release:
    needs: deploy-repository
    if: github.repository == 'BarbossHack/Signal-Desktop-Fedora'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          merge-multiple: true
          path: repo
      - name: Rename artifacts
        run: |
          for f in $(find repo/ -name "*.rpm"); do
            releasever="$(basename "$(dirname "$(dirname "$f")")")"
            base="$(basename ${f%.rpm})"
            IFS=_ read -r name version basearch <<< "$base"
            if [[ "$releasever" =~ ^[0-9]+$ ]]; then
                dist="fc${releasever}"
            else
                dist="${releasever}"
            fi
            mv "$f" "${name}_${version}_${dist}_${basearch}.rpm"
          done
      - name: Create GitHub Release Draft
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create "${GITHUB_REF_NAME}" --repo "$GITHUB_REPOSITORY" --draft
      - name: Upload artifact to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: find . -name "*.rpm" -exec gh release upload "${GITHUB_REF_NAME}" {} --repo "$GITHUB_REPOSITORY" \;
      - name: Publish the release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release edit "${GITHUB_REF_NAME}" --repo "$GITHUB_REPOSITORY" --draft=false
